image: git-registry.hack-hro.de:443/kmohrf/schnipsel/build:buster

stages:
  - test
  - build
  - deploy

make_deb_package:
  stage: build
  tags:
    - fast-io
    - fast-network
  only:
    - tags
    - triggers
    - schedules
    - merge_requests
    - branches
    - web
  script:
    - dpkg-buildpackage --no-sign
    - mkdir -p build/deb
    - mv ../*.deb ../*.changes ../*.buildinfo ../*.git ../*.dsc build/deb
  artifacts:
    paths:
      - build/deb
    expire_in: 1w
