# Generated by Django 2.2.10 on 2020-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200404_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="source",
            field=models.CharField(default="local", max_length=128),
        ),
    ]
