#!/bin/sh

set -eu

EXEC_USER=_schnipsel

. /etc/default/schnipsel

export PYTHONPATH
export DJANGO_SETTINGS_MODULE
export SCHNIPSEL_DATA_DIR

if [ "$(id -nu)" = "$EXEC_USER" ]; then
    exec python3 -m schnipsel "$@"
elif [ "$(id -u)" = 0 ]; then
    exec su -s "$0" "$EXEC_USER" -- "$@"
else
    echo "please run $(basename "$0") as root or '$EXEC_USER'" >&2
    exit 1
fi
